arinwest/urls.py
from django.conf.urls import url

from . import views

app_name = 'arinwest'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about$', views.about, name='about'),
	url(r'^portfolio$', views.portfolio, name='portfolio'),	
	url(r'^celebrities$', views.celebrities, name='celebrities'),
	url(r'^contacts$', views.contacts, name='contacts'),
	url(r'^service/(?P<filial_code>[a-z]+)$', views.service, name='service'),
	url(r'^sendemail$', views.sendemail, name='sendemail'),
	url(r'^getinsta$', views.getinsta),
	url(r'^get_staff_member_info$', views.get_staff_member_info),
]

blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^article/(?P<article_id>[0-9]+)$', views.article, name='article'),
	url(r'^tag/(?P<tag_code>[a-z]+)$', views.tagfilter, name='tagfilter'),
]

'''url(r'^auto/$', views.auto, name='auto'),
	url(r'^project/(?P<project_id>[0-9]+)$', views.project, name='project'),
	url(r'^service/(?P<service_id>[0-9]+)$', views.service, name='service'),
	url(r'^singlecar/(?P<car_id>[0-9]+)$', views.singlecar, name='singlecar'),
	url(r'^sendemail/$', views.sendemail, name='sendemail')'''

mysite/urls.py
from django.conf.urls import (
    url, include, handler404, handler500
)
from django.contrib import admin


handler404 = 'arinwest.views.page_not_found'
handler500 = 'arinwest.views.server_error'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'', include('arinwest.urls')),
]

arinwest/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from blog.models import Tag

# Create your models here.
class StartPage(models.Model):

	class Meta:
		verbose_name = 'Main page'
		verbose_name_plural = 'Version of main page'

	text = models.TextField('Текст на главной')
	is_publish = models.BooleanField('Опубликовать',default=False)

	
	def __unicode__(self):
		return self.text


class PortfolioLevel(models.Model):

	class Meta:
		verbose_name = 'Раздел портфолио'
		verbose_name_plural = 'Разделы портфолио'

	code = models.CharField('Код для фильтра (только латинские символы)',
							max_length=50,
							primary_key=True, 
							unique=True)

	name = models.CharField('Название раздела портфолио', max_length=50)
	tag = models.OneToOneField(Tag, related_name="portfolio_level", null=True)
	numeric = models.IntegerField('Порядковый номер', default=0)

	def __unicode__(self):
		return self.code

	
class PortfolioItem(models.Model):

	class Meta:
		verbose_name = 'Элемент портфолио'
		verbose_name_plural = 'Элементы портфолио'

	name = models.CharField('Название элемента портфолио', 
							max_length=50, 
							blank=True)
	description = models.CharField('Описание элемента портфолио', 
									max_length=250,
									blank=True)
	url_img = models.CharField('Ссылка на фотографию элемента портфолио', 
								max_length=250,
								help_text = 'arinwest/img/portfolio/[level_name]/[file_name].jpg')
	filter_name = models.ForeignKey(PortfolioLevel,
									verbose_name='Код фильтра', 
									on_delete=models.CASCADE,
									help_text='Выберите из существующих')
	article_url = models.CharField('Ссылка на пост в блоге', 
							   max_length=100,
							   help_text='blog/article/[article_number]',
							   blank=True)
	def __unicode__(self):
		return self.name

class Filial(models.Model):
	code = models.CharField('Код для фильтра (только латинские символы)',
							max_length=50,
							primary_key=True, 
							unique=True)
	adress = models.CharField('Адрес',
							  max_length=200,
							  help_text='[населённый пункт], [улица], [номер дома]')
	name = models.CharField('Город',
							max_length=50,
							help_text='Населённый пункт в котором находится салон',
							unique=True)
	user_insta = models.CharField('Instagram User ID',
							max_length=20,
							blank=True)
	user_insta_token = models.CharField('Instagram access token',
							max_length=100,
							blank=True)

	def __unicode__(self):
		return 'Arin West ' + self.name

class Service(models.Model):

	class Meta:
		verbose_name = 'Элемент раздела "Категория услуг"'
		verbose_name_plural = 'Элементы раздела "Категория услуг"'
	name = models.CharField('Название категории услуги',max_length=100)
	description = models.TextField('Описание категории услуги',
								   blank=True)
	img_url = models.CharField('Ссылка на фотографию', 
							   max_length=200,
							   help_text='arinwest/img/service/[file_name].jpg')
	filial = models.ForeignKey(Filial, 
								   on_delete=models.CASCADE,
								   related_name='services',
								   to_field='name')
	info = models.TextField('Информационная справка',
							 blank=True)
	article = models.CharField('Ссылка статью об услуге', 
						   			max_length=250,
						   			help_text='blog/article/[article_number]',
						   			blank=True)
	article_href_text = models.TextField('Текст ссылки на статью в блоге',
							 			blank=True)
	code = models.CharField('Код для создания ссылки (только латинские символы)',
							max_length=50)

	def __unicode__(self):
		return self.name + ' ' + self.filial.name

class ServiceSublevel(models.Model):
	class Meta:
		verbose_name = "Подуровень категории услуг"
		verbose_name_plural = "Подуровни категории услуг"
	name = models.CharField('Название подуровня',max_length=100)
	description = models.TextField('Описание подуровня', blank=True)
	crm_id = models.CharField('ID в системе y-clients',max_length=100, blank=True)
	sublevel_type = models.IntegerField(default=1, editable=False)
	coast = models.CharField('Стоимость',max_length=20, blank=True)
	service = models.ForeignKey(Service, 
								on_delete=models.CASCADE,
								related_name='sublevels')
	def __unicode__(self):
		return self.name


class ServiceSublevelLine(models.Model):
	class Meta:
		verbose_name = 'Элемент подуровня'
		verbose_name_plural = 'Элементы подуровня'
	text = models.CharField('Название услуги', max_length=50, help_text='Название услуги')
	coast = models.CharField('Стоимость',max_length=20)
	service_sub = models.ForeignKey(ServiceSublevel, 
									on_delete=models.CASCADE,
									related_name='coastlines')

	def __unicode__(self):
		return self.text

class AboutPage(models.Model):
	class Meta:
		verbose_name = 'About Page'
	insta_img = models.IntegerField('Колличество фото из инстаграмма', default=10)

	def __unicode__(self):
		return "О Нас"

class ImgForSliderFilial(models.Model):
	class Meta:
		verbose_name = 'Фото для слайдера'
		verbose_name_plural = 'Фото для слайдера'
	filial = models.ForeignKey(Filial, on_delete=models.CASCADE, related_name='imgs_for_slider')
	img_url = models.CharField('Ссылка на фотографию', 
							   max_length=100,
							   help_text='arinwest/img/filials/[filial_name]/[file_name].jpg')

	def __unicode__(self):
		return self.img_url


class StaffMember(models.Model):
	class Meta:
		verbose_name = 'Master'
		verbose_name_plural = 'Masters'
	name = models.CharField('Фамилия Имя',max_length=100)
	post = models.CharField('Должность',max_length=100)
	crm_id = models.CharField('ID в системе y-clients',max_length=100, blank=True)
	img_url = models.CharField('Ссылка на фотографию мастера', 
							   max_length=200,
							   help_text='arinwest/img/about/staff/[file_name].jpg')
	about_page = models.ForeignKey(AboutPage, on_delete=models.CASCADE)
	filial = models.ForeignKey(Filial, 
								   on_delete=models.CASCADE,
								   related_name='masters',
								   to_field='name')
	hash_tag = models.CharField('Хэштэг в инстаграмме',max_length=100,
											blank=True)
	article = models.TextField('Заметка о мастере', blank=True)
	tags = models.ManyToManyField(Tag, 
								  related_name='masters', 
								  verbose_name='Тэги')

class Celebrity(models.Model):
	class Meta:
		verbose_name = 'Celebrity'
		verbose_name_plural = 'Celebrities'
	name = models.CharField('Фамилия Имя',max_length=100)
	post = models.CharField('Род деятельности',max_length=100)
	img_url = models.CharField('Ссылка на фотографию', 
							   max_length=200,
							   help_text='arinwest/img/celebrities/[file_name].jpg')
	article = models.TextField('Описание процедур')
	insta_href = models.CharField('Ссылка пост в инстаграме', 
							   		max_length=100,
							   		blank=True)

	def __unicode__(self):
		return self.name

arinwest/views.py
# -*- coding: utf-8 -*-
import urllib2
import json

from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, Http404
from django.core.mail import mail_managers
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.template import RequestContext
from django.db.models import Count

from .models import StartPage, PortfolioLevel, PortfolioItem, Service, AboutPage, Filial, StaffMember, Celebrity


def index(request):
	try:
		main_text = StartPage.objects.get(is_publish=True)
	except StartPage.DoesNotExist:
		main_text = {'text' : "***Выберите текст на главную***"} 
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} for filial in Filial.objects.all()])
	return render(request, 'arinwest/index.html', {'main_text' : main_text,
												   'services_items' : services_items})

def about(request):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} for filial in Filial.objects.all()])
	about_us_page = AboutPage.objects.get()
	filials = Filial.objects.all()
	filial_max_members = Filial.objects\
							   .annotate(num_masters=Count('masters'))\
							   .order_by('-num_masters')[0]
	
	filial_code = filial_max_members.code
	
	return render(request, 'arinwest/about.html', {'services_items' : services_items,
												   'about_us_page' : about_us_page,
												   'filial_code' : filial_code,
												   'filials' : filials})
def add_preview(url):
	url_list = url.split('/')
	return '/'.join((url_list[:-1])+(['preview',url_list[-1]]))

def portfolio(request):
	portfolio_levels = PortfolioLevel.objects.order_by('numeric')
	portfolio_queryset = PortfolioItem.objects.all()
	portfolio_items = ([{'item': portfolio_item, 
						 'item_preview': add_preview(portfolio_item.url_img)}
						  for portfolio_item in portfolio_queryset ])
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} for filial in Filial.objects.all()])

	return render(request, 'arinwest/portfolio.html', {'portfolio_levels' : portfolio_levels,
													   'portfolio_items' : portfolio_items,
													   'services_items' : services_items})
def service(request, filial_code):
	services = Service.objects.filter(filial__code=filial_code)
	filial_item = Filial.objects.get(code=filial_code)
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} for filial in Filial.objects.all()])
	
	return render(request, 'arinwest/service.html', {'services' : services,
												     'services_items' : services_items,
												     'filial' : filial_item})
def celebrities(request):
	celebrities = Celebrity.objects.all()
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} for filial in Filial.objects.all()])
	return render(request, 'arinwest/celebrities.html', {'services_items' : services_items,
														 'celebrities' : celebrities})

def contacts(request):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} for filial in Filial.objects.all()])
	return render(request, 'arinwest/contacts.html', {'services_items' : services_items})

def sendemail(request):
	if request.method == 'GET':
		raise Http404
	subject = request.POST.get('subject')
	name = request.POST.get('name')
	comments = request.POST.get('message')
	email = request.POST.get('email')

	msg = u'name: {}\nmessage: {}\nemail: {}\n'.format(
													name,
													comments,
													email)
	try:
		mail_managers(subject, msg)
	except Exception:	
 		return HttpResponse({'Error'})
 	else:
 		return HttpResponse({'OK'})

@csrf_exempt
def getinsta(request):
	if request.method == 'GET':
		raise Http404
	filial_code = request.POST.get('filial')[1:]
	filial_choice = get_object_or_404(Filial, code=filial_code)
	url = "https://api.instagram.com/v1/users/{}/media/recent/?access_token={}".format(
		filial_choice.user_insta, filial_choice.user_insta_token)

	response = urllib2.urlopen(url)
	insta_data = json.loads(response.read())
	
	thumbnail_data = ([{'img_url': item['images']['thumbnail']['url'], 
		'url' : item['link']} for item in insta_data['data'] if item['attribution'] == None])

	insta_img_count = AboutPage.objects.get().insta_img;

	thumbnail_data = thumbnail_data[:insta_img_count]
	return render(request, 'arinwest/insta_collage.html', {'thumbnail_data' : thumbnail_data})

@csrf_exempt
def get_staff_member_info(request):
	if request.method == 'GET':
		raise Http404
	name = request.POST.get('name')
	staff_member_get = get_object_or_404(StaffMember, name=name)
	staff_member = {"name" : staff_member_get.name,
					"post" : staff_member_get.post,
					"img_url" : staff_member_get.img_url,
					"article" : staff_member_get.article,
					"tags" :  staff_member_get.tags}
	return render(request,'arinwest/staff_member_info.html', {'staff_member' : staff_member})

def page_not_found(request):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)}
						for filial in Filial.objects.all()])
	response = render_to_response(
	'arinwest/error.html',
	{'services_items': services_items,
	 'title': 'Страница не найдена',
	 'text': 'Запрашиваемая вами страница не найдена.'},
	context_instance=RequestContext(request)
	)

	response.status_code = 404

	return response

def server_error(request):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)}
						for filial in Filial.objects.all()])
	response = render_to_response(
	'arinwest/error.html',
	{'services_items': services_items,
	 'title': 'Ошибка на сервере',
	 'text': 'К сожалению мы не можем обработать ваш запрос.'},
	context_instance=RequestContext(request)
	)

	response.status_code = 500

	return response

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from arinwest.models import Service, Filial
from .models import Article, Tag

ARTICLES_ON_PAGE = 3

# Create your views here.
def index(request):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)}
						 for filial in Filial.objects.all()])
	articles_full_list = Article.objects.order_by('-pub_date')
	paginator = Paginator(articles_full_list, ARTICLES_ON_PAGE)
	tags = Tag.objects.all()

	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	articles_list = ([{'article': article, 
					   'img_preview': article.images.get(is_preview=True),
					   'text_preview': ' '.join(article.text.split()[:50])} for article in articles])
	return render(request, 'blog/blog.html', {'services_items' : services_items,
											  'articles_list' : articles_list,
											  'articles': articles,
											  'tags': tags})

def article(request, article_id):
	article = get_object_or_404(Article, pk=article_id)
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} 
						for filial in Filial.objects.all()])
	similar_articles_list = Article.objects.filter(
		tags__name__in=[tag.name for tag in article.tags.all()]).exclude(
		id=article_id).order_by('-pub_date')
	similar_articles = ([{'similar_article': similar_article, 
					   'img_preview': similar_article.images.get(is_preview=True)} 
					   for similar_article in similar_articles_list])
	
	return render(request, 'blog/article.html', {'services_items' : services_items,
												 'article' : article,
												 'similar_articles' : similar_articles})

def tagfilter(request, tag_code):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)}
						 for filial in Filial.objects.all()])
	try:
		active_tag = Tag.objects.get(code=tag_code)
	except Tag.DoesNotExist:
		return redirect('/blog/') 
	tags = Tag.objects.all()
	articles_tag_list = Article.objects.filter(tags__code=tag_code).order_by('-pub_date')
	paginator = Paginator(articles_tag_list, ARTICLES_ON_PAGE)
	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	articles_list = ([{'article': article, 
					   'img_preview': article.images.get(is_preview=True),
					   'text_preview': ' '.join(article.text.split()[:50])} for article in articles])
	return render(request, 'blog/blog.html', {'services_items' : services_items,
											  'articles_list' : articles_list,
											  'articles': articles,
											  'tags': tags,
											  'active_tag': active_tag})

arinwest/templates/arinwest/error.html
{% extends "arinwest/base.html" %}
{%load staticfiles %}
{%load humanize %}
{%block content%}
    {% include "arinwest/header.html" with header_type=""%}
        
        
        <!-- HEADER line -->     

        <div class="container">
            <div class="header-empty-space"></div>
            <div class="empty-space col-xs-b35 col-sm-b40"></div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <div class="h2"><b>{{title}}</b></div>
                    <div class="empty-space col-xs-b15"></div>
                    <div class="simple-article large grey">{{text}}</div>
                </div>
            </div>

            <div class="empty-space col-xs-b35 col-sm-b45 col-md-b55"></div>
        </div>

        <!-- content begin -->

        {% include "arinwest/footer.html" %}

        <!-- FOOTER -->
    {% endblock %}


arinwest/templates/arinwest/header.html
{%load staticfiles %}
<!-- HEADER line -->
<header class="type-4 {{header_type}} fixed">
    <div class="container">
        <div class="row">
        	{% if page == "index" %}
            <div class="col-xs-6 col-sm-1 hidden">
            {% else %}
            <div class="col-xs-6 col-sm-1">
            {% endif %}
                {% if header_type == "light" %}
                    <a class="logo" href="/"><img src="{% static 'arinwest/img/logo1.png' %}" alt="" /></a>  
                {% else %}
                    <a class="logo" href="/"><img src="{% static 'arinwest/img/logo.png' %}" alt="" /></a> 
                {% endif %}
            </div>
            {% if page == "index" %}
            <div class="col-xs-12 col-sm-12 index-page-menu text-right">
            {% else %}
            <div class="col-xs-6 col-sm-11 text-right">
            {% endif %}
                <div class="navigation-wrapper">

                    <a class="logo responsive" href="/"><img src="{% static 'arinwest/img/logo.png' %}" alt="" /></a>

                    <div class="navigation-overflow">
                        <nav class="text-left clearfix">
                            <ul>
                            	<li>
                                    <a href="/">Главная</a>                                         
                                </li>
                                <li>
                                    <a href="#" class="ms_booking">Записаться</a>                                      
                                </li>
                                <li>
                                    <a href="{% url 'arinwest:about' %}">О нас</a>                             
                                </li>
                                <li>
                                    <a href="{% url 'arinwest:portfolio' %}">Портфолио</a>
                                </li>
                                <li>
                                    <a href="#">Услуги</a>
                                    <span class="toggle-icon"></span>
                                    <ul>
                                        {% for item in services_items %}
                                        <li>
                                            <a href="{% url 'arinwest:service' item.filial_code %}">Arin West {{ item.filial_name }}</a>
                                            <span class="toggle-icon"></span>
                                            <ul>
                                                {% for service in item.services %}
                                                    <li><a href="{% url 'arinwest:service' item.filial_code %}#{{service.code}}">{{service.name}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                <li>
                                    <a href="{% url 'arinwest:celebrities' %}">Знаменитости</a>
                                </li>
                                <li>
                                    <a href="{% url 'blog:index' %}">Блог</a>                                           
                                </li>
                                <li>
                                    <a href="{% url 'arinwest:contacts' %}">Контакты</a>
                                </li>
                            </ul>
                        </nav>
                        
                    </div>

                    <!--div class="follow style-1">
                        <span class="title"></span>
                            <a class="entry" target="_blank" href="https://www.instagram.com/arinwest_studio/"><i class="fa fa-instagram"></i></a>
                            <a class="entry" target="_blank" href="https://www.youtube.com/channel/UCsH_01YOtsjruDJJj5-MWpw
"><i class="fa fa-youtube"></i></a>
                             <a class="entry" target="_blank" href="https://vk.com/arinwest_studio"><i class="fa fa-vk"></i></a>
                    </div-->
                    <div class="bottom-img">
                        <img class="img-responsive" src="{% static 'arinwest/img/abstact-wave.jpg' %}" alt="" />  
                    </div>
                    
                </div>
                
                <div class="hamburger-icon open-navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                
               
                
            </div>
        </div>
    </div>
            
</header>

arinwest/templates/arinwest/insta_collage.html
{% for thumbnail in thumbnail_data%}
    <a class="thumbnail-line-entry overlay-thumbnail" target="blank" href="{{ thumbnail.url }}">
        <img src="{{ thumbnail.img_url }}" alt="" />
        <img src="{{ thumbnail.img_url }}" alt="" />
    </a>
{% endfor %}

arinwest/templates/arinwest/portfolio.html
{% extends "arinwest/base.html" %}
{% load staticfiles %}
{% block content %}
    {% include "arinwest/header.html" with header_type="" services_items=services_items %}   

        <div class="container">
            <div class="header-empty-space"></div>
            <div class="empty-space col-xs-b20 col-sm-b40"></div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <div class="h2"><b>Портфолио</b></div>
                    <div class="empty-space col-xs-b15"></div>
                    <div class="simple-article large grey">Здесь вы можете посмотреть на то чем мы занимаемся и чем гордимся.</div>
                </div>
            </div>

            <div class="empty-space col-xs-b30 col-sm-b60"></div>

            <div class="sorting-menu style-1 text-center">
                <div class="responsive-filtration-title visible-xs"><i class="fa"></i><b><span class="text">Фильтр</span></b><i class="fa fa-angle-down"></i></div>
                <ul class="responsive-filtration-toggle">
                    <li><a data-filter="*" class="active">Все</a></li>
                    {% for level in portfolio_levels %}
                        <li><a data-filter=".{{level.code}}">{{level.name}}</a></li>
                    {% endfor %}
                </ul>
                <div class="empty-space col-xs-b20"></div>
                
            </div>
            <div id="all" class="simple-article text-center portfolio-article active">
                <a href="{% url 'blog:index' %}">Узнать подробнее о процедурах <i class="fa fa-graduation-cap"></i></a>
            </div>
            
            {% for level in portfolio_levels %}
                <div id="{{level.code}}" class="simple-article text-center portfolio-article">
                    <a href="{% url 'blog:tagfilter' level.tag.code %}" >Узнать подробности о процедуре <i class="fa fa-graduation-cap"></i></a>
                </div>
            {% endfor %}
            <div class="empty-space col-xs-b40 col-sm-b25 col-md-b15"></div>
        </div>

        <div class="portfolio-1-wrapper">
            <div class="sorting-container portfolio-1">
                <div class="grid-sizer"></div>
                {% for portfolio_item in portfolio_items %}
                    <div class="sorting-item {{portfolio_item.item.filter_name}}">
                        <div class="homepage-portfolio-preview-1 new-animation">
                            <a class="lightbox" href="{% static portfolio_item.item.url_img %}">
                                <span class="background full-size" style="background-image: url({% static portfolio_item.item_preview %});"></span>
                                <span class="text">
                                    <span class="h4 light"><b>{{portfolio_item.item.name}}</b></span>
                                    <span class="empty-space col-xs-b15"></span>
                                    <span class="simple-article large light transparent ">{{portfolio_item.item.description}}</span>
                                </span>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        {% include "arinwest/footer.html" %}
    {% endblock %}

    
    {% block script %}
    <script src="{% static 'arinwest/js/isotope.pkgd.min.js'%}"></script>
    <script>
        $(function(){
            $(window).load(function(){

                var $container = $('.sorting-container').isotope({
                    itemSelector: '.sorting-item',
                    masonry: {
                        columnWidth: '.grid-sizer'
                    }
                });

                $('.sorting-menu a').click(function() {
                    if($(this).hasClass('active')) return false;
                    $(this).parent().parent().find('.active').removeClass('active');
                    $(this).addClass('active');
                    $(this).closest('.sorting-menu').find('.responsive-filtration-title .text').text($(this).text());
                    var filterValue = $(this).attr('data-filter');
                    $container.isotope({ filter: filterValue });
                });

            });
        });
    </script>

    <script src="{% static 'arinwest/js/simple-lightbox.min.js' %}"></script>
    <script src="{% static 'arinwest/js/portfolio.js' %}"></script>
    <script>

        $(function(){
            var lightbox = $('.lightbox').simpleLightbox({
                disableScroll: false
            });
        });

    </script>
    {% endblock %}


arinwest/templates/arinwest/staff_member_info.html
{%load staticfiles %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<div class="row">
    		<div class="col-md-6">
    			<img class="img-responsive" src="{% static staff_member.img_url %}"/>
    		</div>
    		<div class="col-md-6 text-center">
    			<div class="empty-space col-xs-b15"></div>
    			<div class="h2 small light"><b class="text-popup-title">{{staff_member.name}}</b></div>
		        <div class="empty-space col-xs-b15"></div>
		        <div class="simple-article light transparent text-popup-message blog-light-color">{{staff_member.post}}</div>
		        <div class="empty-space col-xs-b15"></div>
		        <div class="simple-article light">{{staff_member.article}}</div>
		        <div class="empty-space col-xs-b20"></div>
		        <div class="h6 article-options-title light blog-light-color"><b>ТЭГИ</b></div>
                    {% for tag in staff_member.tags.all %}
                        <a class="tag-button" href="{% url 'blog:tagfilter' tag.code %}">{{ tag.name }}</a>
                    {% endfor %}
                <div class="empty-space col-xs-b20 col-sm-b0"></div>
		    </div>
    	</div>
        
    </div>
</div>