blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^article/(?P<article_id>[0-9]+)$', views.article, name='article'),
	url(r'^tag/(?P<tag_code>[a-z]+)$', views.tagfilter, name='tagfilter'),
]

'''url(r'^auto/$', views.auto, name='auto'),
	url(r'^project/(?P<project_id>[0-9]+)$', views.project, name='project'),
	url(r'^service/(?P<service_id>[0-9]+)$', views.service, name='service'),
	url(r'^singlecar/(?P<car_id>[0-9]+)$', views.singlecar, name='singlecar'),
	url(r'^sendemail/$', views.sendemail, name='sendemail')'''

mysite/urls.py
from django.conf.urls import (
    url, include, handler404, handler500
)
from django.contrib import admin


handler404 = 'arinwest.views.page_not_found'
handler500 = 'arinwest.views.server_error'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'', include('arinwest.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Author(models.Model):

	name = models.CharField('Фамилия Имя',max_length=100)
	img_url = models.CharField('Ссылка на аватар', 
							   max_length=190,
							   help_text='blog/img/authors/[file_name].jpg')
	def __unicode__(self):
		return self.name

class Tag(models.Model):

	name = models.CharField('Тэг',
							max_length=50,
							primary_key=True, 
							unique=True)
	code = models.CharField('Код тега (для фильтра, только латинские символы)',
							max_length=50)

	def __unicode__(self):
		return self.name

class Article(models.Model):

	title = models.CharField('Заголовок статьи', max_length=200)
	text = models.TextField('Текст статьи')
	author = models.ForeignKey(Author, 
							   on_delete=models.CASCADE,
							   verbose_name='Автор')
	tags = models.ManyToManyField(Tag, 
								  related_name='articles', 
								  verbose_name='Тэги')
	pub_date = models.DateField('Дата публикации', auto_now_add=True)
	youtube_url = models.CharField('Ссылка на видео', 
							   max_length=250,
							   blank=True)

	def __unicode__(self):
		return " ".join(self.text.split(" ")[:5]) + '...'


class ImageForArticle(models.Model):

	article = models.ForeignKey(Article, 
								on_delete=models.CASCADE,
								related_name='images')
	img_url = models.CharField('Ссылка на фотографию', 
							   max_length=200,
							   help_text='blog/img/articles/[folder_name]/[file_name].jpg')
	is_preview = models.BooleanField('Фото-превью статьи', default=False)

	def __unicode__(self):
		return self.img_url

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from arinwest.models import Service, Filial
from .models import Article, Tag

ARTICLES_ON_PAGE = 3

# Create your views here.
def index(request):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)}
						 for filial in Filial.objects.all()])
	articles_full_list = Article.objects.order_by('-pub_date')
	paginator = Paginator(articles_full_list, ARTICLES_ON_PAGE)
	tags = Tag.objects.all()

	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	articles_list = ([{'article': article, 
					   'img_preview': article.images.get(is_preview=True),
					   'text_preview': ' '.join(article.text.split()[:50])} for article in articles])
	return render(request, 'blog/blog.html', {'services_items' : services_items,
											  'articles_list' : articles_list,
											  'articles': articles,
											  'tags': tags})

def article(request, article_id):
	article = get_object_or_404(Article, pk=article_id)
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)} 
						for filial in Filial.objects.all()])
	similar_articles_list = Article.objects.filter(
		tags__name__in=[tag.name for tag in article.tags.all()]).exclude(
		id=article_id).order_by('-pub_date')
	similar_articles = ([{'similar_article': similar_article, 
					   'img_preview': similar_article.images.get(is_preview=True)} 
					   for similar_article in similar_articles_list])
	
	return render(request, 'blog/article.html', {'services_items' : services_items,
												 'article' : article,
												 'similar_articles' : similar_articles})

def tagfilter(request, tag_code):
	services_items = ([{'filial_name' : filial.name,
						'filial_code' : filial.code,
						'services' : Service.objects.filter(filial__code=filial.code)}
						 for filial in Filial.objects.all()])
	try:
		active_tag = Tag.objects.get(code=tag_code)
	except Tag.DoesNotExist:
		return redirect('/blog/') 
	tags = Tag.objects.all()
	articles_tag_list = Article.objects.filter(tags__code=tag_code).order_by('-pub_date')
	paginator = Paginator(articles_tag_list, ARTICLES_ON_PAGE)
	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	articles_list = ([{'article': article, 
					   'img_preview': article.images.get(is_preview=True),
					   'text_preview': ' '.join(article.text.split()[:50])} for article in articles])
	return render(request, 'blog/blog.html', {'services_items' : services_items,
											  'articles_list' : articles_list,
											  'articles': articles,
											  'tags': tags,
											  'active_tag': active_tag})

blog/templates/blog/article.html
{% extends "arinwest/base.html" %}
{%load staticfiles %}
{% load l10n %}
{%block content%}
    {% include "arinwest/header.html" with header_type="" %}   

        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="column-indent">
                        <div class="header-empty-space"></div>
                        <div class="empty-space col-xs-b55 col-sm-b60"></div>
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 text-center">
                                <div class="h2"><b>Блог</b></div>
                                <div class="empty-space col-xs-b15"></div>
                                <div class="simple-article large grey text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum id metus ac tempus. Praesent ut mauris eget velit volutpat posuere</div>
                            </div>
                        </div>
                        <div class="empty-space col-xs-b55 col-sm-b80"></div>
                        <div class="swiper-container simple-slider">
                            <div class="swiper-button-prev swiper-button hidden-xs style-2"></div>
                            <div class="swiper-button-next swiper-button hidden-xs style-2"></div>
                            <div class="swiper-wrapper">
                                {% for image in article.images.all %}
                                    <div class="swiper-slide" style="background-image: url({% static image.img_url %});"></div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination swiper-pagination-white"></div>
                        </div>

                    </div>
                    <div class="empty-space col-xs-b30"></div>
                    <div class="h3 text-center"><b>{{ article.title }}</b></div>
                    <div class="empty-space col-xs-b15"></div>
                    <div class="simple-article small grey text-center blog-light-color">{{ article.author.name }} / {{article.pub_date|date:"F d, Y"}}</div>
                    <div class="empty-space col-xs-b40"></div>
                    <div class="simple-article grey">
                        <p>{{ article.text|linebreaksbr}}</p>
                      
                        <!--div class="column-indent">
                            <div class="row">
                                <div class="col-xs-4">
                                    <img src="img/blog-detail-13.jpg" alt="">
                                </div>
                                <div class="col-xs-4">
                                    <img src="img/blog-detail-14.jpg" alt="">
                                </div>
                                <div class="col-xs-4">
                                    <img src="img/blog-detail-15.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <br/>
                        <p>Nunc a sapien ut augue dictum dignissim. Aliquam voltpat ipsum tinc,idunt pretium euismod. Nulla quis eros ac dolor rhoncus convallis eget in nisi. Quisque metus ante, consectetur eu velit vitae, pharetra ve stibulum erat. Curabitur non porttitor nulla. In maximus gravida turpis, vitae facilisis nunc hendrerit in. Cras sollicitudin quis metus sit amet porttitor</p>
                        <br/>
                        <br/>
                        <p>Donec vehicula vel justo a semper. Nunc sed facilisis ante. Mauris cursus sit efficijitur venenatis. Aliquam sed lectus eu libero bibendum sagittis. Vivamus est nibh, tincidunt eu purus ut, interdum congue lacus. Qui nisque nisl massa, aliquet at lacius ac, lacinia convallis sit libero. Fusce congue risus magna, id vulputate ante dapibus sed</p>
                        <br/-->
                        
                    </div>
                    {% if article.youtube_url %}
                    <div class="empty-space col-xs-b30"></div>
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 project-video">
                            <div class="video-container">
                                <iframe src="{{ article.youtube_url }}"></iframe>
                            </div> 
                        </div>
                    </div>
                    {% endif %}
                    <div class="empty-space col-xs-b30"></div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="h6 article-options-title blog-light-color"><b>ТЭГИ</b></div>
                                {% for tag in article.tags.all %}
                                    <a class="tag-button" href="{% url 'blog:tagfilter' tag.code %}">{{ tag.name }}</a>
                                {% endfor %}
                            <div class="empty-space col-xs-b20 col-sm-b0"></div>
                        </div>
                        <!--div class="col-sm-6 col-sm-text-right">
                            <div class="follow style-4">
                                <div class="h6 article-options-title"><b>SHARE</b></div>
                                <a class="entry" href="#"><i class="fa fa-instagram"></i></a>
                                <a class="entry" href="#"><i class="fa fa-facebook"></i></a>
                                <a class="entry" href="#"><i class="fa fa-twitter"></i></a>
                                <a class="entry" href="#"><i class="fa fa-google-plus"></i></a>
                                <div class="simple-article small grey article-likes-title blog-light-color"><i class="fa fa-heart"></i> <span class="number">32</span></div>
                            </div>
                        </div-->
                    </div>
                    <div class="empty-space col-xs-b55 col-sm-b60"></div>
                    <div class="h4 text-center"><b>Похожие статьи</b></div>
                    <div class="empty-space col-xs-b30 col-sm-b60"></div>
                    <div class="column-indent">
                        <div class="row">
                            {% for item in similar_articles %}
                                <div class="col-sm-6 col-md-4 blog-entry-clear">
                                    <div class="blog-landing-entry-1 style-1">
                                        <a class="mouseover" style="background-image: url({% static item.img_preview %});" href="{% url 'blog:article' item.similar_article.id %}">
                                            <span class="mouseover-helper-icon"></span>
                                        </a>
                                        <div class="description">
                                            <div class="title">
                                                <a href="{% url 'blog:article' item.similar_article.id %}" class="h4 small blog-mouseover-2"><b>{{ item.similar_article.title }} </b></a>
                                            </div>
                                            <div class="empty-space col-xs-b15"></div>
                                            <div class="simple-article grey small blog-light-color">{{ item.similar_article.author.name }} / {{item.similar_article.pub_date|date:"F d, Y"}}</div>
                                        </div>
                                    </div>
                                    <div class="empty-space col-xs-b30"></div>
                                </div>
                            {% endfor %}
                            <!--div class="col-sm-6 col-md-4 blog-entry-clear">
                                <div class="blog-landing-entry-1 style-1">
                                    <a class="mouseover" style="background-image: url(img/blog-detail-18.jpg);" href="#">
                                        <span class="mouseover-helper-icon"></span>
                                    </a>
                                    <div class="blog-icons">
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <div class="simple-article small light transparent">5 <i class="fa fa-heart-o"></i> 8 <i class="fa fa-comments-o"></i></div>
                                            </div>
                                            <div class="col-xs-6 col-xs-text-right">
                                                <div class="blog-category">design</div>  
                                            </div>
                                        </div>
                                    </div>
                                    <div class="description">
                                        <div class="title">
                                            <a href="#" class="h4 small blog-mouseover-2"><b>QUISQUE PHARETRA DIGNISSIM EX AT ELEMENTUM</b></a>
                                        </div>
                                        <div class="empty-space col-xs-b15"></div>
                                        <div class="simple-article grey small blog-light-color">Goran Ramljak / January 19, 2016</div>
                                    </div>
                                </div>
                                <div class="empty-space col-xs-b30"></div>
                            </div>
                            <div class="col-sm-6 col-md-4 blog-entry-clear">
                                <div class="blog-landing-entry-1 style-1">
                                    <a class="mouseover" style="background-image: url(img/blog-detail-19.jpg);" href="#">
                                        <span class="mouseover-helper-icon"></span>
                                    </a>
                                    <div class="blog-icons">
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <div class="simple-article small light transparent">5 <i class="fa fa-heart-o"></i> 8 <i class="fa fa-comments-o"></i></div>
                                            </div>
                                            <div class="col-xs-6 col-xs-text-right">
                                                <div class="blog-category">design</div>  
                                            </div>
                                        </div>
                                    </div>
                                    <div class="description">
                                        <div class="title">
                                            <a href="#" class="h4 small blog-mouseover-2"><b>QUISQUE PHARETRA DIGNISSIM EX AT ELEMENTUM</b></a>
                                        </div>
                                        <div class="empty-space col-xs-b15"></div>
                                        <div class="simple-article grey small blog-light-color">Goran Ramljak / January 19, 2016</div>
                                    </div>
                                </div>
                                <div class="empty-space col-xs-b30"></div>
                            </div-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        {% include "arinwest/footer.html" %}
    {% endblock %}
        

blog/templates/blog/blog.html
{% extends "arinwest/base.html" %}
{%load staticfiles %}
{% load l10n %}
{%block content%}
    {% include "arinwest/header.html" with header_type="" %}
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="column-indent">
                        <div class="header-empty-space"></div>
                        <div class="empty-space col-xs-b20 col-sm-b40"></div>
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 text-center">
                                <div class="h2"><b>Блог</b></div>
                                <div class="empty-space col-xs-b15"></div>
                                <div class="simple-article large grey text-center">Текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст </div>
                                <div class="empty-space col-xs-b25 col-sm-b50"></div>
                                <ul class="list-inline tag-cloud">
                                    {% if active_tag %}
                                        {% for tag in tags.all %}
                                            {% if active_tag.code == tag.code %} 
                                                <li><a class="tag-button active" href="{% url 'blog:tagfilter' tag.code %}">{{ tag.name }}</a></li>
                                            {% else %}
                                                <li><a class="tag-button" href="{% url 'blog:tagfilter' tag.code %}">{{ tag.name }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        {% for tag in tags.all %}
                                            <li><a class="tag-button" href="{% url 'blog:tagfilter' tag.code %}">{{ tag.name }}</a></li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                        <div class="empty-space col-xs-b25 col-sm-b50"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="container-fluid"> 
            {% for item in articles_list %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-landing-entry-3 clearfix {% cycle ' ' 'new-view' %}">
                            <div class="left">
                                <div class="full-size mouseover valign-middle" style="background-image: url({% static item.img_preview %});">
                                    <span class="mouseover-helper-frame"></span>
                                    <div class="valign-text-wrapper">
                                        <div class="align">
                                            <!--<div class="simple-article small light transparent">5 <i class="fa fa-heart-o"></i> 8 <i class="fa fa-comments-o"></i></div>-->
                                            <div class="empty-space col-xs-b15"></div>
                                            <a class="h3 light blog-mouseover-1" href="{% url 'blog:article' item.article.id %}"><b>{{ item.article.title|title }}</b></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="right clearfix">
                                <div class="text">
                                    <div class="cell-view">
                                        <div class="simple-article large grey blog-light-color">
                                            <div class="inline-tags">
                                                {% for tag in item.article.tags.all %}
                                                    <a href="{% url 'blog:tagfilter' tag.code %}">{{ tag.name|title }} </a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="empty-space col-xs-b15"></div>
                                        <div class="simple-article large grey">{{ item.text_preview}} ...</div>
                                    </div>
                                </div>
                                <div class="avatar-wrapper">
                                    <img class="avatar-entry" src="{% static  item.article.author.img_url %}" alt="" />
                                    <div class="empty-space col-xs-b20"></div>
                                    <div class="simple-article grey small blog-light-color">{{ item.article.author.name }}</div>
                                </div>
                            </div>
                            <div class="middle-wrapper">
                                <div class="simple-article light large blog-light-color">{{ item.article.pub_date|date:"d M"}}<br/>{{ item.article.pub_date|date:"Y"}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
           
        </div>

        <div class="container">
            <div class="empty-space col-xs-b55 col-sm-b110"></div>
            <div class="page-pagination">
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number }}">Предыдущая</a>
                {% endif %}
                {% for num in articles.paginator.page_range %}
                    {% if num == articles.number %}
                        <a class="active"><b>{{ num }}</b></a>
                    {% else %}
                        <a href="?page={{ num }}"> {{ num }}</a>
                    {% endif %} 
                {% endfor %}
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}">Следующая</a>
                {% endif %}
            </div>
            <div class="empty-space col-xs-b55 col-sm-b80"></div>
        </div>

        {% include "arinwest/footer.html" %}
    {% endblock %}
        